name: PDF Readme

on:
  push:
    paths:
    - '**.md'

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    
    - name: Install Pdflatex
      run: sudo apt-get install texlive-latex-extra texlive-latex-base librsvg2-bin pandoc

    - name: Create .pdf
      run : cat README.md | sed '/<!--ts-->/,/<!--te-->/d' | pandoc --metadata-file=metadata.yaml -t latex -o README.pdf -N --toc


    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README.pdf
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: master
          branch: readme-patches
          delete-branch: true
          title: '[README.pdf] Update report'
          body: |
            Update report
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: polyrod
          reviewers: polyrod
          team-reviewers: |
            owners
            maintainers
          draft: false

       
