name: Convert PDF to Markdown

on:
  push:
    paths:
    - '**.md'

      jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    
    - name: Create .pdf
      uses: docker://pandoc/core:2.9
      with:
        args: >-  # allows you to break string into multiple lines
            --toc
            -N
            -t pdf
            Readme.md
            metadata.yaml
            -o README.pdf

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        # The token is built in to actions. No config required.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add .pdf files.
        PULL_REQUEST_TITLE: Add .pdf files.
        PULL_REQUEST_BRANCH: pdf-add
        PULL_REQUEST_BODY: Here are the .pdf files you requested.
        PULL_REQUEST_REVIEWERS: polyrod
